version: "3.8"

networks:
  ZenitharNetwork:
    driver: bridge

services:
  postgres:
    networks:
      - ZenitharNetwork
    image: postgres:latest
    container_name: auth_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data

  zenithar:
    networks:
      - ZenitharNetwork
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports: 
      - 8080:8080
    volumes: 
      - .:/app 
    depends_on:
      - postgres

volumes:
  db:
  